# Generated by Django 3.0.6 on 2020-05-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_pic',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
