# Generated by Django 3.0.6 on 2020-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_image_image_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Architecture', 'Architecture'), ('Fashion', 'Fashion'), ('Arts', 'Arts')], default='Travel', max_length=30),
        ),
    ]
